### ISSUE TITLE
Unexpected exit: duplicate peer id

### ISSUE THREAD

**Issue by zhufengme** [EasyTier/EasyTier#225]
My EasyTier service encountered an unexpected exit today, with the following error message:

panic occurred: PanicInfo { payload: Any { .. }, message: Some(duplicate peer id), location: Location { file: "easytier/src/peers/peer_ospf_route.rs", line: 1075, col: 17 }, can_unwind: true, force_no_backtrace: false }

I thoroughly checked my configuration and all nodes, and no found any configuration errors.

**Comment by KKRainbow** [comment]
how many devices in your virtual net

**Comment by zhufengme** [comment]
devices? or peers? 

11 peers in my virtual network, and the number is still increasing.

**Comment by KKRainbow** [comment]
peer id is an uint32, and will randomly pick on startup.
in current design, peer id confict may happen with a very low probability, and can only be handled by restart easytier.

i think this can be improved by silently restart easytier components instead of whole process, this may be done in future version

**Comment by zhufengme** [comment]
thanks, I understand. 

This problem seem very random. I'm even worried that the nodes might be abused by others, even though I used the whitelist parameters from version 1.2

**Comment by KKRainbow** [comment]
no, the confiction only happend in the same virtual net, and also without secret, other user can not do any impact on your network
